version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: monthly
    groups:
      patch-updates:
        update-types: ["patch"]
      minor-updates:
        update-types: ["minor"]
    labels:
      - "dependencies"
    commit-message:
      prefix: "build"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    exclude-paths:
      - .github/workflows/release.yml
      - .github/workflows/scan.yml
    labels:
      - "dependencies"
    commit-message:
      prefix: "ci"
